services:
  app:
    build: .
    container_name: devops-app

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:mysql://devops-db:3306/devopsapp?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: secret
      DDL_AUTO: create

    depends_on:
      db:
        condition: service_healthy

    networks:
      - devops-network

  db:
    image: mysql:8.0
    container_name: devops-db

    environment:
      MYSQL_DATABASE: devopsapp
      MYSQL_ROOT_PASSWORD: secret

    ports:
      - "3307:3306"

    volumes:
      - devops-db-data:/var/lib/mysql

    networks:
      - devops-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  devops-network:
    driver: bridge

volumes:
  devops-db-data: